name: finverse
description: A simple personal asset management app (Finverse).
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    

  provider: ^6.0.5
  sqflite: ^2.2.8+4
  path_provider: ^2.0.14
  path: ^1.8.3
  intl: ^0.20.2
  fl_chart: ^0.68.0
  device_preview: ^1.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
